-- AlterTable
ALTER TABLE "public"."Employee" ADD COLUMN     "isACTIVE" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "isMANAGER" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "isPARTNER" BOOLEAN NOT NULL DEFAULT false;
